# flashcards :: azure-devops

name: $(date:yyyyMMdd)


trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/angular.yaml
    - .azure/stages/aspnet.yaml
    - FlashCard
    - FlashCard*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/stages/angular.yaml
    - .azure/stages/aspnet.yaml
    - FlashCard
    - FlashCard*

stages:
- template: ./stages/angular.yaml

- template: ./stages/aspnet.yaml

